In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import cv2
import os
import pickle
import random
import keras
import imageio

Using TensorFlow backend.


In [3]:
# baseline model for the dogs vs cats dataset
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# baseline model with dropout for the dogs vs cats dataset
from keras.layers import Dropout

In [4]:
from keras.datasets import cifar10
#importing other required libraries
import numpy as np
import pandas as pd
from sklearn.utils.multiclass import unique_labels
import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
#import seaborn as sns
import itertools
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras import Sequential
from keras.applications import VGG19 #For Transfer Learning
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import SGD,Adam
from keras.callbacks import ReduceLROnPlateau
from keras.layers import Flatten,Dense,BatchNormalization,Activation,Dropout
from keras.utils import to_categorical

In [5]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

## fold-1

In [6]:
x_train = np.load('pannuke\\Fold_1\\images\\images.npy')

In [7]:
y_train = np.load('pannuke\\Fold_1\\images\\types.npy')

In [8]:
y_train1 = y_train

In [9]:
y_train2 = y_train

### One Hot Encode with scikit-learn

In [10]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [11]:
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(y_train1)
print(integer_encoded)

print(y_train1)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[3 3 3 ... 5 5 5]
['Breast' 'Breast' 'Breast' ... 'Colon' 'Colon' 'Colon']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [12]:
y_train2 = onehot_encoded

In [13]:
# inception-V3 model used for transfer learning  with 50 epoch
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
#from keras.applications.vgg16 import VGG16
from keras.applications.inception_v3 import InceptionV3
from keras.models import Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# define cnn model
def define_model():
	# load model
	model = InceptionV3(include_top=False, input_shape=(256, 256, 3))
	# mark loaded layers as not trainable
	for layer in model.layers:
		layer.trainable = False
	# add new classifier layers
	flat1 = Flatten()(model.layers[-1].output)
	class1 = Dense(256, activation='relu', kernel_initializer='he_uniform')(flat1)
	output = Dense(19, activation='softmax')(class1)
	# define new model
	model = Model(inputs=model.inputs, outputs=output)
	# compile model
	opt = SGD(lr=0.001, momentum=0.9)
	model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
	#model.summary()
	return model


# run the test harness for evaluating a model
def run_test_harness():
	# define model
	model = define_model()
	# create data generator
	datagen = ImageDataGenerator(featurewise_center=True)
	# specify imagenet mean values for centering
	datagen.mean = [123.68, 116.779, 103.939]
	# fit model
	history = model.fit(x_train, y_train2, batch_size=16, epochs=50, verbose=1)
	# evaluate model
	_, acc = model.evaluate(x_train, y_train2, verbose=1)
	print('> %.3f' % (acc * 100.0))


# entry point, run the test harness
run_test_harness()

Epoch 1/50
2656/2656 [==============================] - 34s 13ms/step - loss: 2.0700 - accuracy: 0.4149
Epoch 2/50
2656/2656 [==============================] - 20s 7ms/step - loss: 1.5383 - accuracy: 0.5448
Epoch 3/50
2656/2656 [==============================] - 20s 8ms/step - loss: 1.2717 - accuracy: 0.6103
Epoch 4/50
2656/2656 [==============================] - 19s 7ms/step - loss: 0.9982 - accuracy: 0.6928
Epoch 5/50
2656/2656 [==============================] - 20s 7ms/step - loss: 0.7950 - accuracy: 0.7590
Epoch 6/50
2656/2656 [==============================] - 20s 7ms/step - loss: 0.6194 - accuracy: 0.8095
Epoch 7/50
2656/2656 [==============================] - 20s 7ms/step - loss: 0.5046 - accuracy: 0.8453
Epoch 8/50
2656/2656 [==============================] - 20s 7ms/step - loss: 0.3841 - accuracy: 0.8840
Epoch 9/50
2656/2656 [==============================] - 20s 7ms/step - loss: 0.3088 - accuracy: 0.9036
Epoch 10/50
2656/2656 [==============================] - 20s 7ms/step - 

In [14]:
# inception-V3 model used for transfer learning  with 200 epoch
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.applications.inception_v3 import InceptionV3
from keras.models import Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# define cnn model
def define_model():
	# load model
	model = InceptionV3(include_top=False, input_shape=(256, 256, 3))
	# mark loaded layers as not trainable
	for layer in model.layers:
		layer.trainable = False
	# add new classifier layers
	flat1 = Flatten()(model.layers[-1].output)
	class1 = Dense(128, activation='relu', kernel_initializer='he_uniform')(flat1)
	output = Dense(19, activation='softmax')(class1)
	# define new model
	model = Model(inputs=model.inputs, outputs=output)
	# compile model
	opt = SGD(lr=0.001, momentum=0.9)
	model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
	#model.summary()
	return model


# run the test harness for evaluating a model
def run_test_harness():
	# define model
	model = define_model()
	# create data generator
	datagen = ImageDataGenerator(featurewise_center=True)
	# specify imagenet mean values for centering
	datagen.mean = [123.68, 116.779, 103.939]
	# fit model
	history = model.fit(x_train, y_train2, batch_size=16, epochs=200, verbose=1)
	_, acc = model.evaluate(x_train, y_train2, verbose=1)
	print('> %.3f' % (acc * 100.0))
	# save model
	model.save('try2 inception.h5')


# entry point, run the test harness
run_test_harness()

Epoch 1/200
2656/2656 [==============================] - 25s 9ms/step - loss: 2.1289 - accuracy: 0.3998
Epoch 2/200
2656/2656 [==============================] - 19s 7ms/step - loss: 1.7689 - accuracy: 0.4846
Epoch 3/200
2656/2656 [==============================] - 19s 7ms/step - loss: 1.5366 - accuracy: 0.5384
Epoch 4/200
2656/2656 [==============================] - 19s 7ms/step - loss: 1.3169 - accuracy: 0.5986
Epoch 5/200
2656/2656 [==============================] - 19s 7ms/step - loss: 1.1525 - accuracy: 0.6472
Epoch 6/200
2656/2656 [==============================] - 19s 7ms/step - loss: 0.9734 - accuracy: 0.6965
Epoch 7/200
2656/2656 [==============================] - 19s 7ms/step - loss: 0.8073 - accuracy: 0.7477
Epoch 8/200
2656/2656 [==============================] - 19s 7ms/step - loss: 0.6689 - accuracy: 0.7974
Epoch 9/200
2656/2656 [==============================] - 19s 7ms/step - loss: 0.6015 - accuracy: 0.8110
Epoch 10/200
2656/2656 [==============================] - 19s 7m

2656/2656 [==============================] - 19s 7ms/step - loss: 0.0499 - accuracy: 0.9831
Epoch 80/200
2656/2656 [==============================] - 19s 7ms/step - loss: 0.0372 - accuracy: 0.9891
Epoch 81/200
2656/2656 [==============================] - 19s 7ms/step - loss: 0.0228 - accuracy: 0.9921
Epoch 82/200
2656/2656 [==============================] - 19s 7ms/step - loss: 0.0381 - accuracy: 0.9895
Epoch 83/200
2656/2656 [==============================] - 19s 7ms/step - loss: 0.0411 - accuracy: 0.9864
Epoch 84/200
2656/2656 [==============================] - 19s 7ms/step - loss: 0.0411 - accuracy: 0.9880
Epoch 85/200
2656/2656 [==============================] - 19s 7ms/step - loss: 0.0189 - accuracy: 0.9940
Epoch 86/200
2656/2656 [==============================] - 19s 7ms/step - loss: 0.0453 - accuracy: 0.9872
Epoch 87/200
2656/2656 [==============================] - 19s 7ms/step - loss: 0.0279 - accuracy: 0.9917
Epoch 88/200
2656/2656 [==============================] - 19s 7ms/st