In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import cv2
import os
import pickle
import random
import keras
import imageio

Using TensorFlow backend.


In [3]:
# baseline model for the dogs vs cats dataset
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# baseline model with dropout for the dogs vs cats dataset
from keras.layers import Dropout

In [4]:
from keras.datasets import cifar10
#importing other required libraries
import numpy as np
import pandas as pd
from sklearn.utils.multiclass import unique_labels
import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
#import seaborn as sns
import itertools
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras import Sequential
from keras.applications import VGG19 #For Transfer Learning
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import SGD,Adam
from keras.callbacks import ReduceLROnPlateau
from keras.layers import Flatten,Dense,BatchNormalization,Activation,Dropout
from keras.utils import to_categorical

In [5]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

## fold-1

In [6]:
x_train = np.load('pannuke\\Fold_1\\images\\images.npy')

In [7]:
y_train = np.load('pannuke\\Fold_1\\images\\types.npy')

In [8]:
y_train1 = y_train

In [9]:
y_train2 = y_train

### One Hot Encode with scikit-learn

In [10]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [11]:
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(y_train1)
print(integer_encoded)

print(y_train1)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[3 3 3 ... 5 5 5]
['Breast' 'Breast' 'Breast' ... 'Colon' 'Colon' 'Colon']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [12]:
y_train2 = onehot_encoded

# DenseNet121

In [13]:
# DenseNet121 model used for transfer learning  with 10 epoch
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.applications import DenseNet121
from keras.models import Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# define cnn model
def define_model():
	# load model
	model = DenseNet121(include_top=False, input_shape=(256, 256, 3))
	# mark loaded layers as not trainable
	for layer in model.layers:
		layer.trainable = False
	# add new classifier layers
	flat1 = Flatten()(model.layers[-1].output)
	class1 = Dense(128, activation='relu', kernel_initializer='he_uniform')(flat1)
	output = Dense(19, activation='softmax')(class1)
	# define new model
	model = Model(inputs=model.inputs, outputs=output)
	# compile model
	opt = SGD(lr=0.001, momentum=0.9)
	model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
	#model.summary()
	return model


# run the test harness for evaluating a model
def run_test_harness():
	# define model
	model = define_model()
	# create data generator
	datagen = ImageDataGenerator(featurewise_center=True)
	# specify imagenet mean values for centering
	datagen.mean = [123.68, 116.779, 103.939]
	# fit model
	history = model.fit(x_train, y_train2, epochs=10, verbose=1)
	# evaluate model
	_, acc = model.evaluate(x_train, y_train2, verbose=1)
	print('> %.3f' % (acc * 100.0))
	# save model
	model.save('try00 DenseNet121.h5')


# entry point, run the test harness
run_test_harness()

29089792/29084464 [==============================] - 58s 2us/step
Epoch 1/10
2656/2656 [==============================] - 42s 16ms/step - loss: 1.9220 - accuracy: 0.4665
Epoch 2/10
2656/2656 [==============================] - 28s 11ms/step - loss: 1.1618 - accuracy: 0.6532
Epoch 3/10
2656/2656 [==============================] - 27s 10ms/step - loss: 0.6005 - accuracy: 0.8268
Epoch 4/10
2656/2656 [==============================] - 26s 10ms/step - loss: 0.2365 - accuracy: 0.9435
Epoch 5/10
2656/2656 [==============================] - 26s 10ms/step - loss: 0.1068 - accuracy: 0.9778
Epoch 6/10
2656/2656 [==============================] - 26s 10ms/step - loss: 0.0528 - accuracy: 0.9936
Epoch 7/10
2656/2656 [==============================] - 26s 10ms/step - loss: 0.0341 - accuracy: 0.9940
Epoch 8/10
2656/2656 [==============================] - 26s 10ms/step - loss: 0.0186 - accuracy: 0.9992
Epoch 9/10
2656/2656 [==============================] - 26s 10ms/step - loss: 0.0159 - accuracy: 0.998

# DenseNet160

In [14]:
# DenseNet60 model used for transfer learning  with 10 epoch
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.applications import DenseNet160
from keras.models import Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# define cnn model
def define_model():
	# load model
	model = DenseNet160(include_top=False, input_shape=(256, 256, 3))
	# mark loaded layers as not trainable
	for layer in model.layers:
		layer.trainable = False
	# add new classifier layers
	flat1 = Flatten()(model.layers[-1].output)
	class1 = Dense(128, activation='relu', kernel_initializer='he_uniform')(flat1)
	output = Dense(19, activation='softmax')(class1)
	# define new model
	model = Model(inputs=model.inputs, outputs=output)
	# compile model
	opt = SGD(lr=0.001, momentum=0.9)
	model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
	#model.summary()
	return model


# run the test harness for evaluating a model
def run_test_harness():
	# define model
	model = define_model()
	# create data generator
	datagen = ImageDataGenerator(featurewise_center=True)
	# specify imagenet mean values for centering
	datagen.mean = [123.68, 116.779, 103.939]
	# fit model
	history = model.fit(x_train, y_train2, epochs=10, verbose=1)
	# evaluate model
	_, acc = model.evaluate(x_train, y_train2, verbose=1)
	print('> %.3f' % (acc * 100.0))
	# save model
	model.save('try00 DenseNet160.h5')


# entry point, run the test harness
run_test_harness()

ImportError: cannot import name 'DenseNet160'

# DenseNet201

In [15]:
# DenseNet201 model used for transfer learning  with 10 epoch
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.applications import DenseNet201
from keras.models import Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# define cnn model
def define_model():
	# load model
	model = DenseNet201(include_top=False, input_shape=(256, 256, 3))
	# mark loaded layers as not trainable
	for layer in model.layers:
		layer.trainable = False
	# add new classifier layers
	flat1 = Flatten()(model.layers[-1].output)
	class1 = Dense(128, activation='relu', kernel_initializer='he_uniform')(flat1)
	output = Dense(19, activation='softmax')(class1)
	# define new model
	model = Model(inputs=model.inputs, outputs=output)
	# compile model
	opt = SGD(lr=0.001, momentum=0.9)
	model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
	#model.summary()
	return model


# run the test harness for evaluating a model
def run_test_harness():
	# define model
	model = define_model()
	# create data generator
	datagen = ImageDataGenerator(featurewise_center=True)
	# specify imagenet mean values for centering
	datagen.mean = [123.68, 116.779, 103.939]
	# fit model
	history = model.fit(x_train, y_train2, epochs=10, verbose=1)
	# evaluate model
	_, acc = model.evaluate(x_train, y_train2, verbose=1)
	print('> %.3f' % (acc * 100.0))
	# save model
	model.save('try00 DenseNet121.h5')


# entry point, run the test harness
run_test_harness()

74842112/74836368 [==============================] - 239s 3us/step
Epoch 1/10
2656/2656 [==============================] - 632s 238ms/step - loss: 1.8227 - accuracy: 0.4996
Epoch 2/10
2656/2656 [==============================] - 43s 16ms/step - loss: 1.0377 - accuracy: 0.6905
Epoch 3/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.4175 - accuracy: 0.8795
Epoch 4/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.1714 - accuracy: 0.9642
Epoch 5/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.0600 - accuracy: 0.9917
Epoch 6/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.0363 - accuracy: 0.9959
Epoch 7/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.0233 - accuracy: 0.9985
Epoch 8/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.0170 - accuracy: 0.9981
Epoch 9/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.0139 - accuracy: 0.