In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import cv2
import os
import pickle
import random
import keras
import imageio

Using TensorFlow backend.


In [3]:
# baseline model for the dogs vs cats dataset
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# baseline model with dropout for the dogs vs cats dataset
from keras.layers import Dropout

In [4]:
from keras.datasets import cifar10
#importing other required libraries
import numpy as np
import pandas as pd
from sklearn.utils.multiclass import unique_labels
import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
#import seaborn as sns
import itertools
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras import Sequential
from keras.applications import VGG19 #For Transfer Learning
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import SGD,Adam
from keras.callbacks import ReduceLROnPlateau
from keras.layers import Flatten,Dense,BatchNormalization,Activation,Dropout
from keras.utils import to_categorical

In [5]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

## fold-1

In [6]:
x_train = np.load('pannuke\\Fold_1\\images\\images.npy')

In [7]:
y_train = np.load('pannuke\\Fold_1\\images\\types.npy')

In [8]:
y_train1 = y_train

In [9]:
y_train2 = y_train

### One Hot Encode with scikit-learn

In [10]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [11]:
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(y_train1)
print(integer_encoded)

print(y_train1)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[3 3 3 ... 5 5 5]
['Breast' 'Breast' 'Breast' ... 'Colon' 'Colon' 'Colon']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [12]:
y_train2 = onehot_encoded

# EfficientNet (Xception)

In [13]:
# Xception model used for transfer learning  with 10 epoch
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from tensorflow.keras.applications import Xception
from keras.models import Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# define cnn model
def define_model():
	# load model
	model = Xception(include_top=False, input_shape=(256, 256, 3))
	# mark loaded layers as not trainable
	for layer in model.layers:
		layer.trainable = False
	# add new classifier layers
	flat1 = Flatten()(model.layers[-1].output)
	class1 = Dense(128, activation='relu', kernel_initializer='he_uniform')(flat1)
	output = Dense(19, activation='softmax')(class1)
	# define new model
	model = Model(inputs=model.inputs, outputs=output)
	# compile model
	opt = SGD(lr=0.001, momentum=0.9)
	model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
	#model.summary()
	return model


# run the test harness for evaluating a model
def run_test_harness():
	# define model
	model = define_model()
	# create data generator
	datagen = ImageDataGenerator(featurewise_center=True)
	# specify imagenet mean values for centering
	datagen.mean = [123.68, 116.779, 103.939]
	# fit model
	history = model.fit(x_train, y_train2, epochs=10, verbose=1)
	# evaluate model
	_, acc = model.evaluate(x_train, y_train2, verbose=1)
	print('> %.3f' % (acc * 100.0))
	# save model
	model.save('try00 Xception.h5')


# entry point, run the test harness
run_test_harness()

83689472/83683744 [==============================] - 163s 2us/step


AttributeError: 'Node' object has no attribute 'output_masks'

# DenseNet160

In [14]:
# DenseNet60 model used for transfer learning  with 10 epoch
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.applications import DenseNet160
from keras.models import Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# define cnn model
def define_model():
	# load model
	model = DenseNet160(include_top=False, input_shape=(256, 256, 3))
	# mark loaded layers as not trainable
	for layer in model.layers:
		layer.trainable = False
	# add new classifier layers
	flat1 = Flatten()(model.layers[-1].output)
	class1 = Dense(128, activation='relu', kernel_initializer='he_uniform')(flat1)
	output = Dense(19, activation='softmax')(class1)
	# define new model
	model = Model(inputs=model.inputs, outputs=output)
	# compile model
	opt = SGD(lr=0.001, momentum=0.9)
	model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
	#model.summary()
	return model


# run the test harness for evaluating a model
def run_test_harness():
	# define model
	model = define_model()
	# create data generator
	datagen = ImageDataGenerator(featurewise_center=True)
	# specify imagenet mean values for centering
	datagen.mean = [123.68, 116.779, 103.939]
	# fit model
	history = model.fit(x_train, y_train2, epochs=10, verbose=1)
	# evaluate model
	_, acc = model.evaluate(x_train, y_train2, verbose=1)
	print('> %.3f' % (acc * 100.0))
	# save model
	model.save('try00 DenseNet160.h5')


# entry point, run the test harness
run_test_harness()

ImportError: cannot import name 'DenseNet160'

In [15]:
# ResNet50 model used for transfer learning  with 20 epoch
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.applications import ResNet50
from keras.models import Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# define cnn model
def define_model():
	# load model
	model = ResNet50(include_top=False, input_shape=(256, 256, 3))
	# mark loaded layers as not trainable
	for layer in model.layers:
		layer.trainable = False
	# add new classifier layers
	flat1 = Flatten()(model.layers[-1].output)
	class1 = Dense(128, activation='relu', kernel_initializer='he_uniform')(flat1)
	output = Dense(19, activation='softmax')(class1)
	# define new model
	model = Model(inputs=model.inputs, outputs=output)
	# compile model
	opt = SGD(lr=0.001, momentum=0.9)
	model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
	#model.summary()
	return model


# run the test harness for evaluating a model
def run_test_harness():
	# define model
	model = define_model()
	# create data generator
	datagen = ImageDataGenerator(featurewise_center=True)
	# specify imagenet mean values for centering
	datagen.mean = [123.68, 116.779, 103.939]
	# fit model
	history = model.fit(x_train, y_train2, epochs=20, verbose=1)
	# evaluate model
	_, acc = model.evaluate(x_train, y_train2, verbose=1)
	print('> %.3f' % (acc * 100.0))
	# save model
	model.save('try0 resnet.h5')


# entry point, run the test harness
run_test_harness()

C:\Users\ACER\Documents\ML_DL_projects\project3\env\lib\site-packages\keras_applications\resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '


Epoch 1/20
2656/2656 [==============================] - 27s 10ms/step - loss: 1.6752 - accuracy: 0.5354
Epoch 2/20
2656/2656 [==============================] - 25s 10ms/step - loss: 0.4466 - accuracy: 0.8671
Epoch 3/20
2656/2656 [==============================] - 25s 10ms/step - loss: 0.0786 - accuracy: 0.9849
Epoch 4/20
2656/2656 [==============================] - 25s 9ms/step - loss: 0.0246 - accuracy: 0.9955
Epoch 5/20
2656/2656 [==============================] - 25s 10ms/step - loss: 0.0177 - accuracy: 0.9970
Epoch 6/20
2656/2656 [==============================] - 25s 9ms/step - loss: 0.0125 - accuracy: 0.9981
Epoch 7/20
2656/2656 [==============================] - 25s 9ms/step - loss: 0.0065 - accuracy: 0.9992
Epoch 8/20
2656/2656 [==============================] - 25s 10ms/step - loss: 0.0077 - accuracy: 0.9992
Epoch 9/20
2656/2656 [==============================] - 26s 10ms/step - loss: 0.0041 - accuracy: 0.9996
Epoch 10/20
2656/2656 [==============================] - 26s 10ms/s

In [14]:
# ResNet50 model used for transfer learning  with 50 epoch
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.applications import ResNet50
from keras.models import Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# define cnn model
def define_model():
	# load model
	model = ResNet50(include_top=False, input_shape=(256, 256, 3))
	# mark loaded layers as not trainable
	for layer in model.layers:
		layer.trainable = False
	# add new classifier layers
	flat1 = Flatten()(model.layers[-1].output)
	class1 = Dense(128, activation='relu', kernel_initializer='he_uniform')(flat1)
	output = Dense(19, activation='softmax')(class1)
	# define new model
	model = Model(inputs=model.inputs, outputs=output)
	# compile model
	opt = SGD(lr=0.001, momentum=0.9)
	model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
	#model.summary()
	return model


# run the test harness for evaluating a model
def run_test_harness():
	# define model
	model = define_model()
	# create data generator
	datagen = ImageDataGenerator(featurewise_center=True)
	# specify imagenet mean values for centering
	datagen.mean = [123.68, 116.779, 103.939]
	# fit model
	history = model.fit(x_train, y_train2, epochs=50, verbose=1)
	# evaluate model
	_, acc = model.evaluate(x_train, y_train2, verbose=1)
	print('> %.3f' % (acc * 100.0))
	# save model
	model.save('try1 resnet.h5')


# entry point, run the test harness
run_test_harness()

C:\Users\ACER\Documents\ML_DL_projects\project3\env\lib\site-packages\keras_applications\resnet50.py:265: UserWarning: The output shape of `ResNet50(include_top=False)` has been changed since Keras 2.2.0.
  warnings.warn('The output shape of `ResNet50(include_top=False)` '


94658560/94653016 [==============================] - 390s 4us/step
Epoch 1/50
2656/2656 [==============================] - 40s 15ms/step - loss: 1.7284 - accuracy: 0.5019
Epoch 2/50
2656/2656 [==============================] - 28s 10ms/step - loss: 0.6682 - accuracy: 0.7963
Epoch 3/50
2656/2656 [==============================] - 25s 9ms/step - loss: 0.1737 - accuracy: 0.9526
Epoch 4/50
2656/2656 [==============================] - 25s 9ms/step - loss: 0.0432 - accuracy: 0.9913
Epoch 5/50
2656/2656 [==============================] - 25s 9ms/step - loss: 0.0150 - accuracy: 0.9981
Epoch 6/50
2656/2656 [==============================] - 25s 9ms/step - loss: 0.0102 - accuracy: 0.9989
Epoch 7/50
2656/2656 [==============================] - 26s 10ms/step - loss: 0.0174 - accuracy: 0.9966
Epoch 8/50
2656/2656 [==============================] - 25s 10ms/step - loss: 0.0045 - accuracy: 1.0000
Epoch 9/50
2656/2656 [==============================] - 25s 9ms/step - loss: 0.0051 - accuracy: 0.9985
Ep

In [ ]:
# inception-V3 model used for transfer learning  with 200 epoch
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.applications.inception_v3 import InceptionV3
from keras.models import Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# define cnn model
def define_model():
	# load model
	model = InceptionV3(include_top=False, input_shape=(256, 256, 3))
	# mark loaded layers as not trainable
	for layer in model.layers:
		layer.trainable = False
	# add new classifier layers
	flat1 = Flatten()(model.layers[-1].output)
	class1 = Dense(128, activation='relu', kernel_initializer='he_uniform')(flat1)
	output = Dense(19, activation='softmax')(class1)
	# define new model
	model = Model(inputs=model.inputs, outputs=output)
	# compile model
	opt = SGD(lr=0.001, momentum=0.9)
	model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
	#model.summary()
	return model


# run the test harness for evaluating a model
def run_test_harness():
	# define model
	model = define_model()
	# create data generator
	datagen = ImageDataGenerator(featurewise_center=True)
	# specify imagenet mean values for centering
	datagen.mean = [123.68, 116.779, 103.939]
	# fit model
	history = model.fit(x_train, y_train2, epochs=200, verbose=1)
	_, acc = model.evaluate(x_train, y_train2, verbose=1)
	print('> %.3f' % (acc * 100.0))
	# save model
	model.save('try2 model.h5')


# entry point, run the test harness
run_test_harness()

# DenseNet201

In [15]:
# DenseNet201 model used for transfer learning  with 10 epoch
import sys
from matplotlib import pyplot
from keras.utils import to_categorical
from keras.applications import DenseNet201
from keras.models import Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
from keras.preprocessing.image import ImageDataGenerator

# define cnn model
def define_model():
	# load model
	model = DenseNet201(include_top=False, input_shape=(256, 256, 3))
	# mark loaded layers as not trainable
	for layer in model.layers:
		layer.trainable = False
	# add new classifier layers
	flat1 = Flatten()(model.layers[-1].output)
	class1 = Dense(128, activation='relu', kernel_initializer='he_uniform')(flat1)
	output = Dense(19, activation='softmax')(class1)
	# define new model
	model = Model(inputs=model.inputs, outputs=output)
	# compile model
	opt = SGD(lr=0.001, momentum=0.9)
	model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
	#model.summary()
	return model


# run the test harness for evaluating a model
def run_test_harness():
	# define model
	model = define_model()
	# create data generator
	datagen = ImageDataGenerator(featurewise_center=True)
	# specify imagenet mean values for centering
	datagen.mean = [123.68, 116.779, 103.939]
	# fit model
	history = model.fit(x_train, y_train2, epochs=10, verbose=1)
	# evaluate model
	_, acc = model.evaluate(x_train, y_train2, verbose=1)
	print('> %.3f' % (acc * 100.0))
	# save model
	model.save('try00 DenseNet121.h5')


# entry point, run the test harness
run_test_harness()

74842112/74836368 [==============================] - 239s 3us/step
Epoch 1/10
2656/2656 [==============================] - 632s 238ms/step - loss: 1.8227 - accuracy: 0.4996
Epoch 2/10
2656/2656 [==============================] - 43s 16ms/step - loss: 1.0377 - accuracy: 0.6905
Epoch 3/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.4175 - accuracy: 0.8795
Epoch 4/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.1714 - accuracy: 0.9642
Epoch 5/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.0600 - accuracy: 0.9917
Epoch 6/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.0363 - accuracy: 0.9959
Epoch 7/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.0233 - accuracy: 0.9985
Epoch 8/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.0170 - accuracy: 0.9981
Epoch 9/10
2656/2656 [==============================] - 39s 15ms/step - loss: 0.0139 - accuracy: 0.